name: Playwright Tests
on:
  push:
    branches: [main]

jobs: 
  PlaywrightE2E:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout repository
       uses: actions/checkout@v2
      -name: Say Hello
       run: echo Hello there!